### ISSUE TITLE
How to access page props?

### ISSUE THREAD

**Issue by bolivir** [mohkoma/inertiajs-transform-props#1]
Hi, 

Currently im giving your package a try because i need to transform properties (Transform them to json api spec resources).
The app is using some shared data properties, but as soon as i switch the createInertiaApp with yours it cannot find those properties anymore while using `computed(() => usePage().props.value.auth.user)` for example its just giving undefined.
Switching back to the default createInertiaApp its working fine.

**Comment by mohkoma** [comment]
Hi,
You're correct, I tested it now and it seems that the `usePage()` hook is not working for some reason, But if you could use `$page` property then It should work fine`this.$page.props.value.auth.user`.

**Comment by bolivir** [comment]
Correct me if i am wrong but as far as i know the `$page.props` is not available in templates, or was it when using options api

**Comment by mohkoma** [comment]
No! it is available in the templates and I use it very often

**Comment by bolivir** [comment]
Ok weird, its only working for me when using it inside the view but not in the script tags. Seems to be caused by composition api i think

**Comment by mohkoma** [comment]
Indeed, It could be that the composition api is the reason. But you could wrap it as a computed property and use it in the template.

**Comment by bolivir** [comment]
Thats just problem, for me that does not work. For example ` let a = computed(() => this.$page.props)` just gives undefined.
But if you are saying its working on your side it should be a problem in my setup with the composition api im using.

Edit:
I think the issue for me is that the usePage hook is not working ;) 
https://github.com/inertiajs/inertia/issues/412
